[[on_complete.asr]]
job = "recasepunc"
args = { media_id = "{{args.media_id}}" }

[[on_complete.asr]]
job = "nlp"
args = { post_id = "{{args.media_id|post_id_from_media}}" }

[[on_complete.nlp]]
job = "naive_ned"
args = { post_id = "{{args.post_id}}" }
